import * as React from "react";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import SignIn from "../../module/SignIn/SignIn";
import ProductPage from "../../module/Product/ProductPage";
export default function Product() {
  return (
    <>
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ProductPage />
      </main>
    </>
  );
}
