import SignUpForm from "../../module/SignUp/SignUp";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import * as React from "react";

export default function SignUp() {
  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SignUpForm />
      </main>
    </>
  );
}
