import * as React from "react";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import SignIn from "../../module/SignIn/SignIn";
export default function LogIn() {
  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SignIn />
      </main>
    </>
  );
}
